source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'ViewModelTestingDemo' do
    pod 'AlamofireImage', '~> 3.1'
    pod 'Intrepid', '~> 0.6.1'
    
    target 'ViewModelTestingDemoTests' do
        inherit! :search_paths
        pod 'OHHTTPStubs'
        pod 'OHHTTPStubs/Swift'
    end
    
end
